export const actionType = {
    SET_ITEM: 'SET_ITEM',
    SET_ORIGINAL_ITEM: 'SET_ORIGINAL_ITEM',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    CLEAR_CART: 'CLEAR_CART',
    REMOVE_ITEM: 'REMOVE_ITEM'
}